name: dpvo
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch
  - pytorch-scatter
  - pytorch-cuda=11.7    # ここを修正
  - torchvision
  - pip:
    - tensorboard
    - numba
    - tqdm
    - einops
    - pypose
    - kornia
    - numpy
    - plyfile
    - evo
    - opencv-python
    - yacs

